faster getpoint
yeesian/ArchGDAL.jl pull request #369
Opened 2023-02-22 21:09 UTC by rafaqz

`getpoint` is pretty slow currently, to the point rasterizing a shapefile from ArchGDAL.jl is 20x slower than one from Shapefile.jl. Mostly because getting points allocates every time.

This PR greatly (but not completely) reduces the gap by:
1. Not returning GDAL points. Thery are pretty inefficient when we have thousands of points. A `Tuple` is better.
2. Preallocating `Ref` for `getpoint!` in the iterator returning `Geointerfce.getpoint(linestring)`, and reusing them for each point.

2023-02-24 20:20 UTC, evetion commented
I was slightly hesitant about changing the return type here, but I think this still fits as it qualifies as point.

We could better document that we essentially are changing GeoInterface.coordinates to be a nested Vector of a Tuple instead of a Vector. That has impact on some construction methods as well.

2023-02-24 21:54 UTC, rafaqz commented
Yeah, I tried to optimise the gdal point first but the overhead of allocating them all individually is just really bad.

Once all the methods here accept any point it won't make much difference either.

And yes I've noticed there's still a lot of nested vector around. It would be a good performance gain to swap them all to tuples.

2023-02-24 22:49 UTC, rafaqz commented
Another thought I had writing this is it would be faster to use `getx`, `gety` etc because they don't need allocations at all.

But it assumes trad point order, so I went with `getpoint!`.

2023-02-25 03:03 UTC, yeesian requested changes
I'd err on the side of assuming this is a breaking/major change. 

> There may be more objects that need this treatment. [...] Once all the methods here accept any point it won't make much difference either. [...] And yes I've noticed there's still a lot of nested vector around. It would be a good performance gain to swap them all to tuples.

Can we do it all within a single PR? I don't think it'd be a good idea to have inconsistencies in return types across geometry types.

2023-02-25 16:21 UTC, rafaqz commented
I guess its a breaking change? But calling GeoInerface methods returns a lot of types of points already, and it doesn't promise what kind of point comes from what parent object.

I also doubt it will actually break much.

We should actually put this on `getgeom`  and I guess it's just multipoint missing? I'm not sure that will be faster because it's accessed differently.

2023-03-30 23:44 UTC, yeesian submitted a review, later dismissed
LGTM because of https://github.com/yeesian/ArchGDAL.jl/pull/369#issuecomment-1444409693 --

> I was slightly hesitant about changing the return type here, but I think this still fits as it qualifies as point.

Will get a second opinion from @evetion nevertheless just in case there's anything other context from GeoInterface I might be missing

2023-03-31 11:39 UTC, evetion commented
Do we have a roundtrip test? I.e. `ArchGDAL.createpoint(GeoInterface.getpoint))`? Similarly for `GeoInterface.coordinates`, if this PR changes that.

2023-04-23 15:16 UTC, rafaqz commented
It doesn't touch `coordinates`. But yes round trip on points would be good. I think that should just work already.

2023-05-06 20:36 UTC, visr approved these changes
Nice speedup, looks good to me!

2023-05-06 22:08 UTC, yeesian approved these changes

2023-05-06 22:09 UTC, merged